server:
  port: 8080
  forward-headers-strategy: framework
logging:
  file:
    name: logs/application.log
  level:
    root: INFO
    '[com.diplome.game_recommendation]': DEBUG

spring:
  config:
      import: optional:file:.env[.properties]
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:postgresql://db:5432/game_recommendation
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
minio:
    url: http://localhost:9000
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    bucket: journal-logs
gigachat:
    authorization-key: ${GIGACHAT_KEY}
rawg:
    key: ${RAWG_API_KEY}